-- Run this in your Supabase SQL Editor

-- ============================================================================
-- 1. PROFILES UPDATE (Bio & Website)
-- ============================================================================
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS bio TEXT,
ADD COLUMN IF NOT EXISTS website TEXT;

-- ============================================================================
-- 2. CREATE FOLLOWERS TABLE (If it doesn't exist)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.followers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    following_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(follower_id, following_id)
);

ALTER TABLE public.followers ENABLE ROW LEVEL SECURITY;

-- Followers Policies
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can insert their own follows' AND tablename = 'followers') THEN
        CREATE POLICY "Users can insert their own follows" ON public.followers FOR INSERT WITH CHECK (auth.uid() = follower_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can delete their own follows' AND tablename = 'followers') THEN
        CREATE POLICY "Users can delete their own follows" ON public.followers FOR DELETE USING (auth.uid() = follower_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Anyone can read follows' AND tablename = 'followers') THEN
        CREATE POLICY "Anyone can read follows" ON public.followers FOR SELECT USING (true);
    END IF;
END $$;

-- ============================================================================
-- 3. CREATE NOTIFICATIONS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL, -- The recipient of the notification
    actor_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL, -- The person who performed the action
    type TEXT CHECK (type IN ('like', 'follow', 'comment')) NOT NULL,
    entity_id TEXT, -- Optional ID (e.g., the design_id that was liked)
    is_read BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Notifications Policies
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own notifications' AND tablename = 'notifications') THEN
        CREATE POLICY "Users can view own notifications" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can delete own notifications' AND tablename = 'notifications') THEN
        CREATE POLICY "Users can delete own notifications" ON public.notifications FOR DELETE USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can update own notifications' AND tablename = 'notifications') THEN
        CREATE POLICY "Users can update own notifications" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);
    END IF;
END $$;

-- ============================================================================
-- 4. CREATE TRIGGERS FOR AUTOMATED NOTIFICATIONS
-- ============================================================================

-- Trigger for New Likes
CREATE OR REPLACE FUNCTION public.handle_new_like()
RETURNS TRIGGER AS $$
DECLARE
    design_owner_id UUID;
BEGIN
    SELECT user_id INTO design_owner_id FROM public.designs WHERE id = NEW.design_id;
    
    IF design_owner_id != NEW.user_id THEN
        INSERT INTO public.notifications (user_id, actor_id, type, entity_id)
        VALUES (design_owner_id, NEW.user_id, 'like', NEW.design_id::text);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_like_created ON public.likes;

CREATE TRIGGER on_like_created
AFTER INSERT ON public.likes
FOR EACH ROW EXECUTE FUNCTION public.handle_new_like();


-- Trigger for New Followers
CREATE OR REPLACE FUNCTION public.handle_new_follower()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.notifications (user_id, actor_id, type)
    VALUES (NEW.following_id, NEW.follower_id, 'follow');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_follower_created ON public.followers;

CREATE TRIGGER on_follower_created
AFTER INSERT ON public.followers
FOR EACH ROW EXECUTE FUNCTION public.handle_new_follower();

-- ============================================================================
-- 5. ENABLE REALTIME
-- ============================================================================
-- Note: You might need to adjust this depending on your existing publications,
-- but this ensures realtime is active for notifications.
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'notifications'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
    END IF;
EXCEPTION WHEN OTHERS THEN
    -- Ignore error if publication doesn't exist or table is already added
END $$;
