-- User-submitted moderation reports and support requests.
-- Both tables are private: users may create and read only their own rows.

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC, anon;
GRANT USAGE ON SCHEMA private TO authenticated;

CREATE TABLE public.content_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  design_id BIGINT NOT NULL REFERENCES public.designs(id) ON DELETE CASCADE,
  reason TEXT NOT NULL CHECK (reason IN ('spam', 'harassment', 'copyright', 'unsafe', 'other')),
  details TEXT CHECK (details IS NULL OR char_length(details) <= 1000),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewing', 'resolved', 'dismissed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (reporter_id, design_id)
);

CREATE INDEX idx_content_reports_design_id ON public.content_reports(design_id);
CREATE INDEX idx_content_reports_status_created_at ON public.content_reports(status, created_at DESC);

ALTER TABLE public.content_reports ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.content_reports FROM PUBLIC, anon;
GRANT SELECT, INSERT ON public.content_reports TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.content_reports_id_seq TO authenticated;

CREATE FUNCTION private.can_submit_content_report()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT count(*) < 5
  FROM public.content_reports
  WHERE reporter_id = (SELECT auth.uid())
    AND created_at > now() - INTERVAL '1 minute';
$$;

REVOKE EXECUTE ON FUNCTION private.can_submit_content_report() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION private.can_submit_content_report() TO authenticated;

CREATE POLICY "Users can submit their own reports"
  ON public.content_reports
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT auth.uid()) = reporter_id
    AND private.can_submit_content_report()
  );

CREATE POLICY "Users can view their own reports"
  ON public.content_reports
  FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = reporter_id);

CREATE TABLE public.support_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  topic TEXT NOT NULL CHECK (topic IN ('account', 'privacy', 'technical', 'content', 'other')),
  message TEXT NOT NULL CHECK (char_length(message) BETWEEN 10 AND 2000),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_support_requests_user_id ON public.support_requests(user_id);
CREATE INDEX idx_support_requests_status_created_at ON public.support_requests(status, created_at DESC);

ALTER TABLE public.support_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.support_requests FROM PUBLIC, anon;
GRANT SELECT, INSERT ON public.support_requests TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.support_requests_id_seq TO authenticated;

CREATE FUNCTION private.can_submit_support_request()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT count(*) < 3
  FROM public.support_requests
  WHERE user_id = (SELECT auth.uid())
    AND created_at > now() - INTERVAL '10 minutes';
$$;

REVOKE EXECUTE ON FUNCTION private.can_submit_support_request() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION private.can_submit_support_request() TO authenticated;

CREATE POLICY "Users can submit their own support requests"
  ON public.support_requests
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT auth.uid()) = user_id
    AND private.can_submit_support_request()
  );

CREATE POLICY "Users can view their own support requests"
  ON public.support_requests
  FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);

NOTIFY pgrst, 'reload schema';
