-- Clean reset of test data and seed of 15 standard prompts

-- 1. Truncate existing test tables safely
TRUNCATE TABLE public.likes CASCADE;
TRUNCATE TABLE public.followers CASCADE;
TRUNCATE TABLE public.notifications CASCADE;
TRUNCATE TABLE public.designs CASCADE;
TRUNCATE TABLE public.profiles CASCADE;

-- 2. Insert 15 realistic seed designs into public.designs
INSERT INTO public.designs (id, title, prompt, code_snippet, image_url, gallery, tags, likes_count, views_count, remixes_count, rating, featured, created_at)
VALUES
(
    1,
    'Retro Neon Dashboard UI',
    'A retro-futuristic dashboard interface with glowing green text on a dark CRT monitor background, scanlines visible, chunky 8-bit icons, high contrast, neo-brutalist layout with thick borders, data visualization charts in wireframe style, cyberpunk aesthetic.',
    '<div class="dashboard-container">\n  <nav class="sidebar">\n    <ul>\n      <li class="active"><a href="#">Overview</a></li>\n      <li><a href="#">Analytics</a></li>\n      <li><a href="#">Settings</a></li>\n    </ul>\n  </nav>\n  <main class="content">\n    <div class="card stat-card">\n      <h3>Active Users</h3>\n      <span class="value">12,345</span>\n      <div class="chart-placeholder"></div>\n    </div>\n  </main>\n</div>',
    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Analytics', '#RetroUI', '#NeoBrutalism'],
    482,
    3420,
    128,
    4.9,
    true,
    NOW() - INTERVAL '14 days'
),
(
    2,
    'SaaS Analytics Engine',
    'Modern Neo-Brutalist SaaS Analytics Dashboard with bold yellow & purple accents, thick black 4px borders, hard drop shadows, high contrast revenue metric cards, line charts, and status pills.',
    '<div class="saas-card">\n  <div class="header flex justify-between">\n    <h2>Monthly Recurring Revenue</h2>\n    <span class="badge bg-yellow">$48,250</span>\n  </div>\n  <div class="chart-area">\n    <canvas id="mrrChart"></canvas>\n  </div>\n</div>',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Analytics', '#Developer', '#UI'],
    315,
    2150,
    89,
    4.8,
    true,
    NOW() - INTERVAL '12 days'
),
(
    3,
    'Crypto & Web3 Vault UI',
    'Dark mode crypto wallet interface featuring neon green highlights, crisp balance cards, quick token swap widget, transaction history table, and hard border neo-brutalist styling.',
    '<div class="wallet-card bg-black text-white p-6 border-4 border-white">\n  <span class="text-xs font-mono text-gray-400">Total Portfolio Value</span>\n  <h1 class="text-4xl font-black text-green-400 mt-1">$142,890.50</h1>\n  <div class="flex gap-4 mt-6">\n    <button class="bg-green-400 text-black font-bold px-6 py-3 border-2 border-white">Send</button>\n    <button class="bg-white text-black font-bold px-6 py-3 border-2 border-white">Receive</button>\n  </div>\n</div>',
    'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Developer', '#Trend', '#UI'],
    289,
    1890,
    74,
    4.7,
    false,
    NOW() - INTERVAL '10 days'
),
(
    4,
    'Neo-Brutalist Checkout Page',
    'E-commerce order summary and payment form in pastel pink and electric blue, featuring high contrast input fields, promo code sticker badge, and 3D hard shadow CTA button.',
    '<form class="checkout-form bg-pink-100 p-8 border-4 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">\n  <h2 class="text-2xl font-black uppercase mb-4">Order Summary</h2>\n  <div class="form-group mb-4">\n    <label class="block font-mono font-bold text-xs uppercase mb-1">Cardholder Name</label>\n    <input type="text" class="w-full bg-white border-2 border-black p-3 font-mono" placeholder="Satoshi Nakamoto" />\n  </div>\n  <button class="w-full bg-blue-500 text-white font-black py-4 uppercase border-2 border-black hover:translate-y-1">Pay $129.00</button>\n</form>',
    'https://images.unsplash.com/photo-1556742049-0a67e5621413?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1556742049-0a67e5621413?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Shop', '#UI', '#Trend'],
    198,
    1450,
    52,
    4.6,
    false,
    NOW() - INTERVAL '9 days'
),
(
    5,
    'Mobile Fitness Workout Tracker',
    'Mobile app card design for workout tracking, featuring circular progress ring, heart rate gauge, dark mode with neon lime accents, and activity breakdown list.',
    '<div class="fitness-card bg-neutral-900 text-white p-6 rounded-none border-4 border-lime-400">\n  <div class="flex justify-between items-center mb-6">\n    <h3 class="font-black text-xl text-lime-400">DAILY BURN</h3>\n    <span class="bg-lime-400 text-black px-3 py-1 font-mono font-bold text-xs">850 kcal</span>\n  </div>\n  <div class="progress-bar w-full bg-neutral-800 h-4 border border-lime-400 overflow-hidden">\n    <div class="bg-lime-400 h-full w-[78%]"></div>\n  </div>\n</div>',
    'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Mobile', '#UI', '#Trend'],
    412,
    2980,
    115,
    4.9,
    true,
    NOW() - INTERVAL '8 days'
),
(
    6,
    'AI Command Console & Prompt IDE',
    'Developer-focused AI prompt engineer console with syntax highlighting, token usage counter, model selection dropdown, and terminal execution log window.',
    '<div class="ai-console bg-gray-950 text-green-400 font-mono p-6 border-4 border-gray-700">\n  <div class="status-bar border-b border-gray-800 pb-2 mb-4 flex justify-between">\n    <span>MODEL: gpt-4o-realtime</span>\n    <span>TOKENS: 412 / 8192</span>\n  </div>\n  <pre className="text-xs"><code>> System initialized. Ready for prompt execution.</code></pre>\n</div>',
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Developer', '#Analytics', '#UI'],
    530,
    3890,
    164,
    5.0,
    true,
    NOW() - INTERVAL '7 days'
),
(
    7,
    'Editorial Magazine Article Card',
    'Clean, bold editorial article card layout featuring exaggerated typography, thick black borders, category sticker, reading time indicator, and author signature.',
    '<article class="magazine-card bg-amber-50 p-6 border-4 border-black shadow-[6px_6px_0px_0px_rgba(0,0,0,1)]">\n  <span class="bg-black text-white font-mono text-xs px-3 py-1 uppercase font-bold">Design Trends</span>\n  <h2 class="font-black text-3xl uppercase text-black mt-3 leading-tight">The Death of Bland Minimalist Web Design</h2>\n  <p class="font-mono text-xs text-gray-700 mt-2">5 min read • By @art_director</p>\n</article>',
    'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#UI', '#Trend'],
    165,
    1120,
    38,
    4.5,
    false,
    NOW() - INTERVAL '6 days'
),
(
    8,
    'Cyberpunk Audio Wave Player',
    'Vibrant music player component with interactive waveform visualizer, album cover glow, volume slider, and neo-brutalist playback controls.',
    '<div class="player bg-purple-950 text-purple-200 p-6 border-4 border-pink-500">\n  <div class="track-info mb-4 flex justify-between items-center">\n    <div>\n      <h4 class="font-black text-white text-lg">HYPERDRIVE</h4>\n      <p class="text-xs font-mono text-pink-400">CyberSynth Vol. 4</p>\n    </div>\n    <button class="w-12 h-12 bg-pink-500 text-black font-black border-2 border-white flex items-center justify-center">▶</button>\n  </div>\n</div>',
    'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Mobile', '#UI'],
    240,
    1680,
    63,
    4.7,
    false,
    NOW() - INTERVAL '5 days'
),
(
    9,
    'Fintech Expense Breakdown',
    'Financial budget tracker card with category badges, percentage progress bars, weekly spending limits, and quick add transaction modal button.',
    '<div class="budget-card bg-white p-6 border-4 border-black shadow-[6px_6px_0px_0px_rgba(0,0,0,1)]">\n  <h3 class="font-black text-xl uppercase mb-4">Weekly Budget</h3>\n  <div class="space-y-3 font-mono text-sm">\n    <div class="flex justify-between"><span>Shopping</span><span class="font-bold text-red-500">$340.00</span></div>\n    <div class="flex justify-between"><span>Food & Dining</span><span class="font-bold text-green-600">$185.50</span></div>\n  </div>\n</div>',
    'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Analytics', '#Mobile', '#Shop'],
    210,
    1390,
    49,
    4.6,
    false,
    NOW() - INTERVAL '5 days'
),
(
    10,
    'Developer Documentation Portal',
    'Sleek API documentation sidebar and code viewer widget with copy-to-clipboard button, endpoint HTTP badges (GET, POST), and JSON response pre-tag.',
    '<div class="doc-widget bg-slate-900 text-slate-100 p-6 border-4 border-slate-700 font-mono">\n  <div class="flex items-center gap-2 mb-3">\n    <span class="bg-green-500 text-black px-2 py-0.5 text-xs font-bold">GET</span>\n    <span class="text-sm">/v1/prompts/featured</span>\n  </div>\n  <pre class="bg-black p-4 text-xs text-emerald-400 border border-slate-800"><code>{ "status": 200, "count": 15 }</code></pre>\n</div>',
    'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Developer', '#UI'],
    380,
    2740,
    102,
    4.8,
    true,
    NOW() - INTERVAL '4 days'
),
(
    11,
    'NFT Marketplace Collection Card',
    'Digital art NFT auction card featuring live countdown timer, highest bidder avatar, current ETH price badge, and bold placing bid button.',
    '<div class="nft-card bg-neutral-950 text-white p-5 border-4 border-cyan-400 shadow-[6px_6px_0px_0px_rgba(6,182,212,1)]">\n  <div class="flex justify-between items-center mb-3">\n    <span class="font-mono text-xs text-cyan-400">Current Bid</span>\n    <span class="font-black text-lg text-white">4.85 ETH</span>\n  </div>\n  <button class="w-full bg-cyan-400 text-black font-black py-3 uppercase border-2 border-white">Place Bid</button>\n</div>',
    'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Shop', '#Trend', '#UI'],
    175,
    1240,
    41,
    4.4,
    false,
    NOW() - INTERVAL '3 days'
),
(
    12,
    'Kanban Task Management Card',
    'Project management task card with urgency status pill, avatar stack of assigned team members, progress checklist counter, and drag handle.',
    '<div class="task-card bg-yellow-100 p-5 border-3 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">\n  <div class="flex justify-between mb-2">\n    <span class="bg-red-500 text-white font-mono text-[10px] uppercase font-bold px-2 py-0.5">High Priority</span>\n  </div>\n  <h4 class="font-black text-lg text-black">Refactor Authentication Flow</h4>\n  <p class="font-mono text-xs text-gray-700 mt-1">2 / 5 subtasks completed</p>\n</div>',
    'https://images.unsplash.com/photo-1611224923853-80b023f02d71?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1611224923853-80b023f02d71?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Analytics', '#Developer'],
    295,
    1980,
    79,
    4.7,
    false,
    NOW() - INTERVAL '2 days'
),
(
    13,
    'Cyberpunk Auth & Login Form',
    'High contrast futuristic login screen component with glitch text styling, social login buttons, remember session checkbox, and password visibility toggle.',
    '<div class="auth-box bg-black text-green-400 p-8 border-4 border-green-500 font-mono shadow-[8px_8px_0px_0px_rgba(34,197,94,1)]">\n  <h2 class="text-3xl font-black uppercase text-white mb-6">ACCESS TERMINAL</h2>\n  <input type="email" placeholder="USER_IDENTITY" class="w-full bg-neutral-900 border-2 border-green-500 p-3 mb-4 text-green-400" />\n  <button class="w-full bg-green-500 text-black font-black py-4 uppercase hover:bg-white">AUTHENTICATE</button>\n</div>',
    'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Developer', '#UI', '#RetroUI'],
    440,
    3120,
    132,
    4.9,
    true,
    NOW() - INTERVAL '2 days'
),
(
    14,
    'Food Delivery Mobile Order Card',
    'Mobile app card for food delivery featuring dish thumbnail, star rating badge, estimated delivery countdown, and quick reorder button.',
    '<div class="food-card bg-orange-50 p-4 border-3 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">\n  <div class="flex justify-between items-center mb-2">\n    <h4 class="font-black text-lg text-black">Artisanal Ramen Bowl</h4>\n    <span class="bg-yellow-400 text-black font-mono font-bold text-xs px-2 py-0.5">★ 4.9</span>\n  </div>\n  <p class="font-mono text-xs text-gray-600 mb-4">ETA: 20-30 mins • Free Delivery</p>\n  <button class="w-full bg-black text-white font-bold py-2.5 uppercase text-xs">Reorder $16.50</button>\n</div>',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#Mobile', '#Shop'],
    190,
    1310,
    45,
    4.6,
    false,
    NOW() - INTERVAL '1 day'
),
(
    15,
    'Portfolio Hero Sticker Section',
    'Eye-catching Neo-Brutalist portfolio hero header component with floating sticker badges, bold headline typography, social icon strip, and contact CTA button.',
    '<header class="hero bg-yellow-300 p-12 border-4 border-black text-black shadow-[10px_10px_0px_0px_rgba(0,0,0,1)]">\n  <span class="inline-block bg-black text-yellow-300 font-mono font-bold text-xs px-3 py-1 uppercase mb-4">AVAILABLE FOR FREELANCE</span>\n  <h1 class="font-black text-5xl uppercase leading-none mb-6">CRAFTING DIGITAL ARTISAN UIs</h1>\n  <button class="bg-black text-white font-black text-lg px-8 py-4 uppercase border-2 border-black hover:bg-white hover:text-black">LET''S BUILD</button>\n</header>',
    'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    ARRAY['https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80'],
    ARRAY['#UI', '#Trend', '#Developer'],
    498,
    3560,
    150,
    5.0,
    true,
    NOW() - INTERVAL '1 hour'
);
